# Mini-Projeto: Simulação de Jogo de Dados | Entrega (11/08 - Sexta-feira)

## Objetivo

Você tem a tarefa de criar uma simulação para um jogo de dados. Essa simulação tem como objetivo reunir estatísticas para analisar a justiça do jogo, possíveis resultados e fazer previsões sobre jogos futuros.

## Desafios do Projeto

1. **Simulação de Dados**: Crie uma função que simule o lançamento de dois dados de seis lados (valores de 1 a 6). Esta função deve retornar a soma dos resultados dos dados.

2. **Múltiplas Simulações**: Use a função do passo 1 para simular um grande número de jogos de dados (digamos, 1000 jogos). Armazene o resultado de cada jogo em um array NumPy.

3. **Análise de Dados**: Agora, vamos analisar os resultados desses jogos. Calcule e imprima o seguinte:
- A média dos resultados.
- O lançamento máximo e mínimo.
- O número de vezes que cada possível lançamento (2, 3, 4, 5, 6, 7, 8, 9, 10, 11 e 12) ocorreu.
- Teste de Hipótese: Agora vamos fazer um pouco de teste de hipóteses:
  - Supondo um jogo justo (ou seja, todos os lançamentos são igualmente prováveis), o resultado da sua simulação coincide com essa suposição? Por que sim ou por que não?
  - O que isso significa para um jogador do jogo de dados?

## Entregáveis

Link de um repositório no seu GitHub, contendo:
- Um script Python (arquivo `.py` ou `.ipynb`) com a sua solução para os três desafios apresentados.


In [144]:
import numpy as np

## DEFININDO A FUNÇÃO
def lancamento_dados ():
    dado1 = np.random.randint(1,7) ## GERA DE FORMA RANDOMICA DE 1 A 6 UM NÚMERO ALEATÓRIO DADO 1
    dado2 = np.random.randint(1,7) ## GERA DE FORMA RANDOMICA DE 1 A 6 UM NÚMERO ALEATÓRIO DADO 2
    soma = dado1 + dado2 ## FAZ A SOMA DOS DOIS DADOS.
    return soma ## RETORNA O RESULTADO

qtd_lanc = int(input('Digite a quantidade de simulaçoes desejadas: '))
lista = [] # CRIEI UMA LISTA VAZIA PARA ARMAZENAR OS RESULTADOS.

for _ in range(qtd_lanc): #PERCORRE A QTDA DE LANÇAMENTOS E FAZ O INCREMENTO DOS DA SOMA NA LISTA
    resultado = lancamento_dados()
    lista.append(resultado)

resultados = np.array(lista) # CRIA UM ARRAY

In [145]:
unique_values, counts = np.unique(resultados, return_counts = True) #GERA VALORES UNICOS DO ARRAY E SOMA A QUANTIDADE DE OCORRÊNCIAS

print(f'Esse é o valor máximo da soma dos lançamentos {np.max(resultados)}')
print(f'Esse é o valor mínimo da soma dos lançamentos {np.min(resultados)}')
print(f'Essa é a média arredondada da soma dos lançamentos {round(np.mean(resultados))}')

for valor, contagem in zip(unique_values,counts):
    print(valor, contagem,(contagem/qtd_lanc)*100,'%')
qtd_menor_resultado = np.count_nonzero(resultados == (np.min(resultados)))
qtd_maior_resultado = np.count_nonzero(resultados == (np.max(resultados)))
media = round(np.mean(resultados))
media_cima = round(np.mean(resultados)+1)
media_baixo = round(np.mean(resultados)-1)
qtd_media = np.count_nonzero(resultados == media)
qtd_media_baixo = np.count_nonzero(resultados == media_baixo)
qtd_media_acima = np.count_nonzero(resultados == media_cima)

Esse é o valor máximo da soma dos lançamentos 8
Esse é o valor mínimo da soma dos lançamentos 8
Essa é a média arredondada da soma dos lançamentos 8
8 1 100.0 %


In [146]:
#FAZ A SAÍDA INTELIGENTE DO SISTEMA:

if qtd_lanc >=500:
    print(f'De acordo com a quantidade de lançamentos que foi de: {qtd_lanc}\né possível afetir que o resultado mais provável da soma dos lançamentos dos dados é entre {round(np.mean(resultados))-1} e {round(np.mean(resultados))+1}')
    print(f'Ou seja para o jogador que estiver fazendo o lançamento\ndeverá lembrar que o % de as duas facetas serem iguais dessa simulação é de {((qtd_menor_resultado / qtd_lanc)*100)+((qtd_maior_resultado / qtd_lanc)*100)}%')
    print(f'Pois os extremos que contemplam a marginalidade dos resultados 2 (1:1) e 12 (6:6) são representados em % da seguinte forma:')
    print(f'{np.min(resultados)} : {((qtd_menor_resultado / qtd_lanc)*100)}%')
    print(f'{np.max(resultados)} : {((qtd_maior_resultado / qtd_lanc)*100)}%')
    print(f'E por outro lado os números: {media_baixo,media,media_cima} representam um acumulado de:')
    print(f'{((qtd_media/qtd_lanc)+(qtd_media_baixo/qtd_lanc)+(qtd_media_acima/qtd_lanc))*100}%')
else:
    print(f'Com a quantidade de simulações que foi inserido não é possível realizar uma análise mais profunda, refaça a operação e insira simulações acima de 500')

Com a quantidade de simulações que foi inserido não é possível realizar uma análise mais profunda, refaça a operação e insira simulações acima de 500


# Exercícios de fixação (entrega não obrigatória)

In [71]:
import numpy as np

### 1 | Crie um array com 10 elementos, todos sendo o número 3, usando NumPy
> Resposta esperada: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [72]:
array = np.full(10,3)
print(array)

[3 3 3 3 3 3 3 3 3 3]


### 2 | Crie um array com 20 números aleatórios, e encontre os valores mínimo e máximo naquele array

In [73]:
array_2 = np.random.randint(0,101,20)
print('Array aleatório:', array_2)
print('Array Minimo', np.min(array_2))
print('Array aleatório:', np.max(array_2))


Array aleatório: [99 30 83 33 71 13 66 47  6 61  6 74 51 47 94 22 60 91 22 91]
Array Minimo 6
Array aleatório: 99


### 3 | Adicione 5 para cada elemento do array do exercício 2

In [74]:
# Resolução
new_array = [x + 5 for x in array_2]
print(new_array)


[104, 35, 88, 38, 76, 18, 71, 52, 11, 66, 11, 79, 56, 52, 99, 27, 65, 96, 27, 96]


### 4 | Encontre o index do valor máximo do array do exercício anterior

In [75]:
# Resolução
maior_indice = np.argmax(new_array)
print("Esse é o maior índice:", maior_indice)
print(new_array[maior_indice])

Esse é o maior índice: 0
104


### 5 | Crie dois arrays de tamanho 5 com números inteiros aleatórios de 1 a 10, e depois múltiplique um pelo outro

In [76]:
# Resolução

array1 = np.random.randint(1,11,size=5)
array2 = np.random.randint(1,11,size=5)
resultado = array1 * array2

print("Array 1: " , array1)
print("Array 1: " , array2)
resultado


Array 1:  [ 3  4  8 10  4]
Array 1:  [ 3 10  4  5  1]


array([ 9, 40, 32, 50,  4])

### 6 | Crie um array com 10 elementos, todos sendo o número 1, usando NumPy

In [77]:
# Resolução

array_number_1 = np.ones(10)
array_number_1
int_array_number_1 = array_number_1.astype(int)
int_array_number_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 7 | Mude o terceiro elemento do array do exercício anterior para o número 5

In [78]:
# Resolução

int_array_number_1[2] = 5
int_array_number_1

array([1, 1, 5, 1, 1, 1, 1, 1, 1, 1])

### 8 | Delete o quinto elemento do array do exercícios 6

In [79]:
# Resolução

deletando_5_elemento = np.delete(int_array_number_1,4)
deletando_5_elemento

array([1, 1, 5, 1, 1, 1, 1, 1, 1])

### 9 | Verifique se o número 5 existe no array do exercício 2

In [80]:
# Resolução
existe_o_5 = np.any(deletando_5_elemento == 5)
existe_o_5

True

### 10 | Crie um array de 0 a 30 em incrementos de 2 usando NumPy

In [81]:
# Resolução

array_incremental = np.arange(0,31,2)
array_incremental

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])